name: Build Server

on:
  push:
    branches:
      - main

env:
  # Modify this line to set the link of the server
  HEROKU_LINK: mmoactiongameserver

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Add node dependency
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Adding node modules
      - run: npm install -g typescript;
      - run: npm -f ci;

      # Preparing the build
      - run: npm run build_server
        env:
          CI: ""

      # Copy target and build server to folder server
      - run: mkdir server
      - run: cp -r build-server Cargo* package* tsconfig.json public src Dockerfile .dockerignore server

      # Push the docker file updated
      - name: Docker login
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login -u fisso9900 --password-stdin

      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_SECRET }}
        run: heroku container:login

      - name: Build Docker image
        run: docker build -t registry.heroku.com/$HEROKU_LINK/web:latest .

      - name: Push Docker image
        run: docker push registry.heroku.com/$HEROKU_LINK/web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_SECRET }}
        run: heroku container:release -a $HEROKU_LINK web
